baseurl      = "d2.rs"
title        = "d2"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disableKinds = ["RSS"]


[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  disableReadOtherPosts = false

  enableSharingButtons = false

  description = "devops stuff"
  keywords = "devops, blog"
  images = [""]

  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "talk is cheap, show me the code"
    readOtherPosts = "read other posts"

    [languages.en.params.logo]
      logoText = "d2"
      logoHomeLink = "/"

  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"